# Global settings applied to the whole site.
# [build]
  # command = "npm build"
  # publish = "public"

# build a preview of the site (Drafts and Future dates also)
# [context.deploy-preview]
  # command = "yarn build:preview"

# [build.environment]
#   HUGO_ENV = "development"

[context.master.environment]
  REACT_APP_STAGE = "production"

[context.development.environment]
  REACT_APP_STAGE = "development"
